FROM node:18.17.1

WORKDIR /client
ADD ./webpack.config.js /client/
# ADD ./client/dist /client/dist

RUN \
  npm init -y && \
  npm install --save react react-dom && \
  npm install --save-dev webpack webpack-cli webpack-dev-server babel-loader babel-core babel-preset-react babel-preset-env

CMD /client/node_modules/.bin/webpack-dev-server --hot
