version: '3'

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api:/go/api
    ports:
      - 8080:8080
    depends_on:
      - db
    command: air
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/client:cached
    ports:
      - 3000:3000
    command: "npm run dev"
  db:
    container_name: db
    build:
      context: ./db/
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mdet
      MYSQL_USER: mdet
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql:cached
    platform: linux/amd64
